import React, {useState} from "react";
import styles from './Search.module.css'

const datas = [
    "ARML3",
    "MLAS3",
    "CBAV3",
    "TTEN3",
    "NINJ3",
    "DOTZ3",
    "ATEA3",
    "MODL4",
    "MODL3",
    "VITT3",
    "KRSA3",
    "CXSE3",
    "RIOS3",
    "HCAR3",
    "GGPS3",
    "MATD3",
    "ALLD3",
    "BLAU3",
    "ATMP3",
    "ASAI3",
    "JSLG3",
    "CMIN3",
    "ELMD3",
    "ORVR3",
    "OPCT3",
    "WEST3",
    "CSED3",
    "BMOB3",
    "JALL3",
    "POWE3",
    "MOSI3",
    "MBLY3",
    "ESPA3",
    "VAMO3",
    "INTB3",
    "NGRD3",
    "AVLL3",
    "RRRP3",
    "AERI3",
    "ENJU3",
    "CASH3",
    "TFCO4",
    "CONX3",
    "GMAT3",
    "SEQL3",
    "PASS3",
    "BOAS3",
    "MELK3",
    "HBSA3",
    "CURY3",
    "PLPL3",
    "PETZ3",
    "PGMN3",
    "LAVV3",
    "LJQQ3",
    "DMVF3",
    "SOMA3",
    "RIVA3",
    "AMBP3",
    "ALPK3",
    "MTRE3",
    "MDNE3",
    "VIIA3",
    "RDNI3",
    "SLED3",
    "RSID3",
    "MNDL3",
    "LEVE3",
    "CTKA4",
    "CTKA3",
    "MYPK3",
    "GRND3",
    "LCAM3",
    "CEAB3",
    "LLIS3",
    "CGRA4",
    "CGRA3",
    "ESTR4",
    "ESTR3",
    "DIRR3",
    "CTNM4",
    "CTNM3",
    "EVEN3",
    "AMAR3",
    "MOVI3",
    "JHSF3",
    "HBOR3",
    "PDGR3",
    "EZTC3",
    "SMLS3",
    "RENT3",
    "MRVE3",
    "MGLU3",
    "LREN3",
    "COGN3",
    "WHRL4",
    "WHRL3",
    "TCSA3",
    "SEER3",
    "SLED4",
    "LAME4",
    "LAME3",
    "HOOT4",
    "GFSA3",
    "YDUQ3",
    "CYRE3",
    "CVCB3",
    "PRVA3",
    "SMTO3",
    "MDIA3",
    "CAML3",
    "AGRO3",
    "BSEV3",
    "BEEF3",
    "VIVA3",
    "CRFB3",
    "PCAR3",
    "NTCO3",
    "MRFG3",
    "JBSS3",
    "BRFS3",
    "TRAD3",
    "BSLI4",
    "BSLI3",
    "BTTL3",
    "BPAR3",
    "SCAR3",
    "LPSB3",
    "BMGB4",
    "IGBR3",
    "GSHP3",
    "PSSA3",
    "CARD3",
    "BBRK3",
    "BRPR3",
    "BRSR3",
    "BIDI3",
    "BIDI4",
    "SANB4",
    "SANB3",
    "MULT3",
    "ITUB4",
    "ITUB3",
    "ALSO3",
    "BMIN3",
    "MERC4",
    "LOGG3",
    "ITSA4",
    "IRBR3",
    "IGTA3",
    "BBDC4",
    "BBDC3",
    "BRML3",
    "APER3",
    "BBSE3",
    "BPAN4",
    "BBAS3",
    "DEXP4",
    "DEXP3",
    "PMAM3",
    "FESA4",
    "FESA3",
    "EUCA4",
    "EUCA3",
    "SUZB3",
    "KLBN4",
    "KLBN3",
    "UNIP3",
    "NEMO3",
    "MMXM3",
    "GOAU4",
    "CSNA3",
    "RANI4",
    "BRKM3",
    "BRAP4",
    "BRAP3",
    "GRAO3",
    "AGXY3",
    "CRPG3",
    "SMFT3",
    "SOJA3",
    "ENMT4",
    "ENMT3",
    "HBRE3",
    "RAIZ4",
    "RECV3",
    "PRIO3",
    "OSXB3",
    "DMMO3",
    "RPMG3",
    "UGPA3",
    "PETR4",
    "PETR3",
    "BRDT3",
    "ENAT3",
    "ONCO3",
    "VVEO3",
    "PARD3",
    "BIOM3",
    "BALM4",
    "BALM3",
    "GBIO33",
    "PNVL4",
    "PNVL3",
    "AALR3",
    "ODPV3",
    "RADL3",
    "QUAL3",
    "OFSA3",
    "HYPE3",
    "FLRY3",
    "CLSA3",
    "LVTC3",
    "G2DI33",
    "IFCM3",
    "LWSA3",
    "TOTS3",
    "LINX3",
    "POSI3",
    "BRIT3",
    "FIQE3",
    "DESK3",
    "OIBR4",
    "TIMS3",
    "VIVT4",
    "VIVT3",
    "TELB4",
    "TELB3",
    "CEPE3",
    "CEED4",
    "CEED3",
    "EEEL4",
    "EEEL3",
    "CASN4",
    "CASN3",
    "CEGR3",
    "CEBR3",
    "RNEW4",
    "RNEW3",
    "COCE3",
    "CLSC4",
    "CLSC3",
    "ALUP4",
    "ALUP3",
    "SAPR4",
    "SAPR3",
    "CPRE3",
    "CPLE3",
    "CPFE3",
    "CGAS3",
    "AESB3",
    "NEOE3",
    "TRPL4",
    "TRPL3",
    "EGIE3",
    "TAEE4",
    "TAEE3",
    "SBSP3",
    "GEPA4",
    "GEPA3",
    "CESP3",
    "CMIG4",
    "CMIG3",
    "AFLT3",
    "WEGE3",
    "BKBR3",
    "ABEV3",
    "AMER3",
    "AZUL4",
    "B3SA3"
]

function SearchBar({ placeholder}) {
  const [filteredData, setFilteredData] = useState([]);
  const [wordEntered, setWordEntered] = useState("");

  const handleFilter = (event) => {
    const searchWord = event.target.value;
    setWordEntered(searchWord);
    const newFilter = datas.filter((value) => {
      return value.toUpperCase().includes(searchWord.toUpperCase());
    });


    if (searchWord === "") {
      setFilteredData([]);
    } else {
      setFilteredData(newFilter);
    }
  };

  const clearInput = () => {
    setFilteredData([]);
    setWordEntered("");
  };

  return (
    <div className={styles.search}>
      <div className="searchInputs">
        <input
          type="text"
          placeholder={placeholder}
          value={wordEntered}
          onChange={handleFilter}
        />
        <button className="button green" onClick={clearInput}>X</button>
      </div>
      {filteredData.length != 0 && (
        <div className="dataResult">
          {filteredData.slice(0, 15).map((value, key) => {
            return (
              <a className="dataItem" href={value} target="_blank" key={value}>
                <p>{value} </p>
              </a>
            );
          })}
        </div>
      )}
    </div>
  );
}

export default SearchBar;